### ISSUE TITLE
FR: add conversion from Number/text fields

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-units#2]
It would be great if the field would know how to convert scalar values from a Number or Plain Text field to the value of the Units field.

**Comment by khalwat** [comment]
This is a general problem with Field data:

https://github.com/craftcms/cms/issues/2800

...but yes, I can probably special-case this.

**Comment by khalwat** [comment]
Implemented in 1.0.3:

https://github.com/nystudio107/craft-units/releases/tag/1.0.3

https://github.com/nystudio107/craft-units/commit/8e7398034662f20f1363ab1350551094490ae031
