### ISSUE TITLE
FR: Lay out input / field horizontally

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-units#3]
Looks a little funny stacked.

Even though it would only be 1 row, it might make sense to consider using the `table.editable` markup/styles from Craft's UI. Might more complex types easier down the road (multiple input / feet and inches, etc)

**Comment by khalwat** [comment]
It does, but I was following how the Number field worked, where if they didn't enter a size, it'd be full width.

You're right, it might look nicer as a table-style layout.

PRs welcome!
