### ISSUE TITLE
'Default Measure Type' is empty

### ISSUE THREAD

**Issue by Sjouwke** [nystudio107/craft-units#40]
### Describe the bug
For a recipe app I was looking for a plugin to easily calculate ingredients and convert metric systems.
I Installed this plugin and tried to configure the default settings, but the 'Default Measure Type' dropdown is empty. 
If I do add a Unit field to a section, it works, but I can only select 'Length' measurements.

### To reproduce
Steps to reproduce the behaviour:
1. Install plugin
2. Go to "Settings" > "Plugins" > "Units"
3. Try to select something in the "Default Measure Type" dropdown

### Expected behaviour
I expected all measure types listed in the [https://nystudio107.com/docs/units/#units-reference](https://nystudio107.com/docs/units/#units-reference) would be available in this dropdown.

### Screenshots
<img width="1677" alt="Schermafbeelding 2022-05-04 om 10 58 09" src="https://user-images.githubusercontent.com/33376273/166651234-fa66bf97-19d2-43c8-9bc4-ac8e2c313f94.png">

### Versions
- Plugin version: 1.0.4
- Craft version: 3.7.40

**Comment by khalwat** [comment]
So this ends up being an issue with PHP 8 or later, and the changes in the token parser.

**Comment by khalwat** [comment]
Fixed in:

1.0.4 for Craft 3: https://github.com/nystudio107/craft-units/releases/tag/1.0.5

4.0.0 for Craft 4: https://github.com/nystudio107/craft-units/releases/tag/4.0.0
