### ISSUE TITLE
$defaultMax Setting Error

### ISSUE THREAD

**Issue by samlising** [nystudio107/craft-units#45]
### Describe the bug
The following error comes up when I installed Units v4.0 with Craft 4.3.1:
Typed property nystudio107\units\models\Settings::$defaultMax must not be accessed before initialization

I believe it is because in the Settings.php file $defaultMax has no value set. I set this value to:

public int|null|float $defaultMax = null;

This solved the error for me.

**Comment by khalwat** [comment]
Already fixed (just not tagged for release yet):

https://github.com/nystudio107/craft-units/issues/41

**Comment by hasco0182** [comment]
Is the fix for this issue released yet? I'm still getting this error on Craft 4.4.7.1 with Units 4.0.0.

**Comment by khalwat** [comment]
Released as 4.0.1 -> https://github.com/nystudio107/craft-units/releases/tag/4.0.1
